### PR TITLE
Home Page

### LINKED ISSUE #9: Home Page
I'll make the home page of the Website.

- [x] Navbar
- [ ] Header
- [ ] What is Spaces Lounge?
- [ ] Why Spaces Lounge?
- [x] Footer

### PR DESCRIPTION
**Pull request by alisamadiii**
## Short Description

What we did:
- changed the button.jsx to Button.jsx
```diff
- button.jsx
+ Button.jsx
```

- Deleted all the previous code in `Header.jsx` file and add new one
- Deleted and Added the following files:
```diff
- Information1.jsx
- Information2.jsx
+ Why-Space-Lounge.jsx
+ For-Host.jsx
```

- in the `Website_Info.js` file, there are 2 variables that are for `Why-Space-Lounge.jsx` and `For-Host.jsx`
- added 5 images
 

## Fixes Issue

We might add more features in the future, Let's close this issue and in the future, We make another issue.
Closes #9 

## Screenshots
image

### CODE REVIEW

**Comment by alisamadiii** [comment]
Please Don't merge it Right now.
We are going to use the previous design for the header.

**Comment by alisamadiii** [comment]
There are some issues, I'll fix them by today.

**Comment by Mayank-KS** [comment]
Looks good on most part, just make the changes regarding responsiveness as discussed

**Review by Mayank-KS — APPROVED** [review]
LGTM Thank You

**Pull request merged**
