### PR TITLE
Speaker Dashboard

### LINKED ISSUE #49: [FEATURE] Speaker Dashboard
### Description

We need to make the `Speaker-Dashboard`.

- [ ] Speaker-Dashboard

### Screenshots

image
image

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by alisamadiii**
## Short Description
Files that I made:

- Speaker --- `All the details below`
  - Details.js
  - Scheduled_Twitter.jsx
  - Titles.jsx
  - User.jsx
- Content
   - Host-dashboard.js --- `For the data` 
  
 > **Note**
> I am using a Host-dashboard.js file for fake data.

## Fixes Issue

Closes #49 

## Screenshots
I've made a folder in the components which consist of all the components that I used them for the Host page (`host.js`)
image

## Details.jsx
image
image

## Scheduled_Twitter.jsx
image
image

## Titles.jsx
image
image

## User.jsx
image
image

# host.js
image
image

### CODE REVIEW

**Comment by alisamadiii** [comment]
We also added a very simple 404 page.
Later We'll improve it.
image

**Review by jaynarayan-vaishnav — COMMENTED** [review]
Currently reviewing it will mege it when done 
With checking everything.

**Review by jaynarayan-vaishnav — COMMENTED** [review]
Everythings else LGTM. but should we change the `user's name` to `speaker's name` same for `user's job` as it will make it lot easier to see if the user or a speaker.


image

**Comment by alisamadiii** [comment]
We can merge it Right now, We will add new features in the future.

**Comment by jaynarayan-vaishnav** [comment]
Okay then merging it now 👍🏻

**Review by jaynarayan-vaishnav — APPROVED** [review]
LGTM 👍🏻 great work Ali 🙌🏻.

**Pull request merged**
