### PR TITLE
added footer section

### PR DESCRIPTION
**Pull request by Succyvibe**

### CODE REVIEW

**Comment by Succyvibe** [comment]
@AliReza1083 please review my PR

**Comment by alisamadiii** [comment]
Awesome work...
It's looking nice.

I forgot to tell you that instead of `npm`, we use yarn.

image
Would you please remove the changes in `package-lock.json` & `yarn.lock`?

> **Note**
> There must be only one file changes.

**Comment by Succyvibe** [comment]
Alright I will do that

**Comment by Succyvibe** [comment]
Alright just fixed it and I have pushed the code

**Comment by alisamadiii** [comment]
Thanks for doing that.
Also one more thing, We have to discard the changes in yarn.lock?
because the yarn.lock does not need to be changed.

**Comment by alisamadiii** [comment]
image

All you need is to copy the current `code` in yarn.lock and `paste` it in your yarn.lock file and commit it again.

https://github.com/avie-dev/spaceslounge/blob/main/yarn.lock

**Comment by Succyvibe** [comment]
Alright I would do that

**Comment by Succyvibe** [comment]
Done please check and let me know if everything works fine

**Review by alisamadiii — APPROVED** [review]
LGTM 🎉

**Comment by alisamadiii** [comment]
You did a great job.
Well done.
Thanks for your contribution 🎉

**Comment by Succyvibe** [comment]
Thanks for the opportunity. I would love to connect more and also collaborate with your team

**Comment by alisamadiii** [comment]
That's great,
If there is any issue that remains, We'd let you know.

**Pull request merged**
