### PR TITLE
Revert "Small code review"

### PR DESCRIPTION
**Pull request by avie-dev**
In case you want to revert to the avie-dev/spaceslounge#2. You can merge this.

### CODE REVIEW

**Comment by ctoffanin** [comment]
Haha, you read the message "wait before merging it" too late, right @avie-dev?
I created an issue for the how-to contribute page: naming, etc.
Assign both open issues to me, please.
People will know there is already someone working on them.

**Comment by ctoffanin** [comment]
From the original PR @AliReza1083 

> In this PR:
> 
> - Added the fork step and fixed the git clone command URL in the readme page
> - Updated .gitignore file
> - Renamed folders and components names:
>   - It's good practice to use camel case (HomePage) or kebab case (home-page) for the folders name, Spaces should be avoided
>   - It's good practice to name the component with the capital letter and use camel case (Button, HomePage)
>   - Avoid putting numbers in classes and components' names (Information rather than Information1)

**Comment by ctoffanin** [comment]
@AliReza1083 Don't merge this.
After you read the comments and check what I did change in the previous one https://github.com/avie-dev/spaceslounge/pull/2
If you have questions ... ask

Delete this PR when you're done.

**Review by alisamadiii — COMMENTED** [review]
It is awesome...
LGTM ✌️😉
Thanks @ctoffanin

**Pull request closed without merging**
