### PR TITLE
Updated the website...

### PR DESCRIPTION
**Pull request by alisamadiii**
## Short Description
1. Added a header img 
2. Added files for 404 page  
3. Dark is now the default theme now…

## Screenshots
image

### CODE REVIEW

**Comment by RakeshSangem** [comment]
I feel the logo/icon is repeated. What do you think @avie-dev ?

**Comment by jaynarayan-vaishnav** [comment]
LGTM 🙌🏻

**Review by jaynarayan-vaishnav — APPROVED** [review]
LGTM🙌🏻

**Comment by avie-dev** [comment]
@RakeshSangem it's fine for now. We can change it in phase 2 if ever we find it redundant with all over design,
> I feel the logo/icon is repeated. What do you think @avie-dev ?

**Review by avie-dev — APPROVED** [review]
LGTM 🌹

**Pull request merged**
