### PR TITLE
redesigned the 404 page

### LINKED ISSUE #23: 404 pages
if the user goes to a page which doesn't exist, The page must bring something for the user.
We have to make 404 page.

- [x] Desgin
- [ ] Code
- [ ] Test the website

### PR DESCRIPTION
**Pull request by thevinitgupta**
## Short Description
Redesigned the 404 page as suggested in the Figma designs 

## Fixes Issue
Closes #23 

## Screenshots
Screen Shot 2023-02-10 at 13 11 59
Screen Shot 2023-02-10 at 13 11 50
Screen Shot 2023-02-10 at 13 11 41
Screen Shot 2023-02-10 at 13 10 24

### CODE REVIEW

**Comment by alisamadiii** [comment]
Nice job,
You did a great job.
The texts are too big.
image

**Comment by thevinitgupta** [comment]
Could you suggest the text sizes?

**Comment by alisamadiii** [comment]
> Could you suggest the text sizes?

Maybe, Make it half of the current size.

**Comment by alisamadiii** [comment]
How is it going?

**Review by alisamadiii — APPROVED** [review]
LGTM 🚀

**Comment by alisamadiii** [comment]
You did a great job.
Thanks for your contributions.
I hope to see you again in the future.

**Pull request merged**
