### PR TITLE
linked the Page in footer to home page

### PR DESCRIPTION
**Pull request by rohinish404**
## Changes proposed
linked the Page text in footer to home page.

### CODE REVIEW

**Review by alisamadiii — CHANGES_REQUESTED** [review]
It is looking great.
Would you restore the changes from yarn.lock file?

**Comment by rohinish404** [comment]
Actually i dont know how to restore the changes coz i haven't changed anything in that file.

**Review by alisamadiii — APPROVED** [review]
LGTM 🎉

**Comment by alisamadiii** [comment]
You did a great job.
Hope to see you again in the future.
Thanks for your contributions 🎉

**Comment by rohinish404** [comment]
> You did a great job. Hope to see you again in the future. Thanks for your contributions 🎉

Thank you!! I'll try to make more contributions🙂

**Pull request merged**
